version: '3.8'

services:
  rtmp-rtsp-converter:
    build: .
    ports:
      - "8080:8080"  # HTTP API
      - "8554:8554"  # RTSP
    volumes:
      - ./configs:/root/configs
    environment:
      - GIN_MODE=release
    restart: unless-stopped
    
  # Nginx RTMP server для тестирования
  nginx-rtmp:
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935"  # RTMP
      - "8081:80"    # HTTP для статистики
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

  # VLC для тестирования (опционально)
  vlc-test:
    image: jess/vlc
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    profiles:
      - testing